---
flame_enabled: false
flame_available_externally: "false"

# directories
flame_data_directory: "{{ docker_home }}/flame"

# uid / gid
flame_user_id: "1000"
flame_group_id: "1000"

# network
flame_hostname: "flame"

flame_password: "CHANGEME"
