---
- name: Create Heimdall group
  group:
    name: heimdall
    gid: "{{ heimdall_group_id }}"
    state: present
- name: Create Heimdall user
  user:
    name: heimdall
    uid: "{{ heimdall_user_id }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: heimdall
- name: Create Heimdall Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: heimdall
    group: heimdall
  with_items:
    - "{{ heimdall_data_directory }}"
- name: Create Heimdall container
  docker_container:
    name: heimdall
    image: "{{ heimdall_docker_image }}"
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    volumes:
      - "{{ heimdall_data_directory }}:/config:rw"
    env:
      PUID: "{{ heimdall_user_id }}"
      PGID: "{{ heimdall_group_id }}"
      TZ: "{{ ansible_nas_timezone }}"
      #   ports:
      #     - "{{ heimdall_port_http }}:80"
      #     - "{{ heimdall_port_https }}:443"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 128m
    labels:
      traefik.enable: "true"
      traefik.http.routers.heimdall.entrypoints: "web,websecure"
      traefik.http.routers.heimdall.rule: "Host(`{{ heimdall_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.heimdall.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.heimdall.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.heimdall.loadbalancer.server.port: "80"
      flame.type: application
      flame.name: heimdall
      flame.url: "https://{{ heimdall_hostname }}.{{ ansible_nas_domain }}"
      flame.category: "Dashboards"
      flame.icon: heimdall.png
